apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-user-service
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-user-service
  template:
    metadata:
      labels:
        app: deployment-user-service
    spec:
      containers:
        - image: yanzxu/user-service:{IMAGE_TAG}
          name: user-service
          ports:
            - containerPort: 8091
              protocol: TCP
