apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-user-service
  namespace: dev
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /nfs/data/user-service
    server: 192.168.50.53