apiVersion: v1
kind: Service
metadata:
  name: svc-user-service
  namespace: dev
spec:
  clusterIP: 10.96.0.5 
  ports:
  - port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: deployment-user-service
  type: ClusterIP
