apiVersion: v1
kind: Service
metadata:
  name: svc-user-service # curl svc-user-service:8091/users  in pod is ok
  namespace: dev
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: pod-user-service
