apiVersion: v1
kind: Service
metadata:
  name: svc-user-service # curl svc-user-service:80/users  in pod is ok
  namespace: dev
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pod-user-service
