apiVersion: v1
kind: Service
metadata:
  name: svc-user-service
  namespace: dev
spec:
  clusterIP: 192.168.50.52 #固定svc的内网ip
  ports:
    - port: 9091
      protocol: TCP
      targetPort: 8091
  selector:
    app: deployment-user-service
  type: ClusterIP