apiVersion: v1
kind: Service
metadata:
  name: svc-user-service
  namespace: dev
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: deployment-user-service
