apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bff-service
  namespace: dev
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /nfs/data/bff-service
    server: 192.168.50.53