kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-bff-service
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs