apiVersion: v1
kind: Service
metadata:
  name: svc-bff-service # curl svc-bff-service:80/bff  in pod is ok
  namespace: dev
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pod-bff-service
