server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://yzxu.asuscomm.com:3306/order
    username: root
    password: 906700211
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect