spring:
  application:
    name: store-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://yzxu.asuscomm.com:3306/store
    username: root
    password: 906700211
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect